In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("job_salary_prediction_dataset.csv")

In [18]:
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [19]:
df.tail()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1,127791
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2,154593
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0,75988
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5,90467
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084

In [15]:
df.shape

(250000, 10)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  object
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  object
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  object
 5   company_size      250000 non-null  object
 6   location          250000 non-null  object
 7   remote_work       250000 non-null  object
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), object(6)
memory usage: 19.1+ MB

In [21]:
df.describe()

       experience_years   skills_count  certifications         salary
count     250000.000000  250000.000000   250000.000000  250000.000000
mean          10.005408       9.997812        2.491928  145718.080524
std            6.060602       5.479288        1.706475   37407.952729
min            0.000000       1.000000        0.000000   31867.000000
25%            5.000000       5.000000        1.000000  119358.000000
50%           10.000000      10.000000        2.000000  143453.000000
75%           15.000000      15.000000        4.000000  169492.000000
max           20.000000      19.000000        5.000000  333046.000000

In [22]:
df.isnull().sum()

job_title           0
experience_years    0
education_level     0
skills_count        0
industry            0
company_size        0
location            0
remote_work         0
certifications      0
salary              0
dtype: int64

In [25]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [26]:
df.columns

Index(['job_title', 'experience_years', 'education_level', 'skills_count',
       'industry', 'company_size', 'location', 'remote_work', 'certifications',
       'salary'],
      dtype='object')

In [27]:
df.dtypes

job_title           object
experience_years     int64
education_level     object
skills_count         int64
industry            object
company_size        object
location            object
remote_work         object
certifications       int64
salary               int64
dtype: object

In [30]:
df.nunique()

job_title               12
experience_years        21
education_level          5
skills_count            19
industry                10
company_size             5
location                10
remote_work              3
certifications           6
salary              118956
dtype: int64

In [31]:
text_cols = df.select_dtypes(include='object').columns

for col in text_cols:
    df[col] = df[col].str.strip()

In [32]:
df['job_title'].value_counts().head(10)

job_title
Backend Developer            21125
Cybersecurity Analyst        20959
Product Manager              20950
AI Engineer                  20945
Data Scientist               20890
DevOps Engineer              20889
Software Engineer            20876
Data Analyst                 20722
Cloud Engineer               20686
Machine Learning Engineer    20677
Name: count, dtype: int64

In [33]:
df.groupby('job_title')['salary'].mean()

job_title
AI Engineer                  173498.480640
Backend Developer            139202.768663
Business Analyst             122551.231354
Cloud Engineer               152102.535290
Cybersecurity Analyst        148697.695548
Data Analyst                 119891.696603
Data Scientist               147258.214409
DevOps Engineer              149959.266791
Frontend Developer           132653.842485
Machine Learning Engineer    163022.504570
Product Manager              157594.932029
Software Engineer            141739.521460
Name: salary, dtype: float64

In [34]:
df.groupby('education_level')['salary'].mean()

education_level
Bachelor       142410.531291
Diploma        137158.574976
High School    131715.336243
Master         153305.307833
PhD            163976.005295
Name: salary, dtype: float64

In [35]:
df.groupby('industry')['salary'].mean()

industry
Consulting       145451.638293
Education        145993.564547
Finance          145801.639468
Government       145613.869242
Healthcare       145759.995702
Manufacturing    145530.603301
Media            145891.271071
Retail           145399.699408
Technology       145863.808377
Telecom          145876.511967
Name: salary, dtype: float64

In [36]:
df.nlargest(10, 'salary')

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
240392,AI Engineer,20,PhD,11,Consulting,Enterprise,USA,Yes,4,333046
177309,AI Engineer,19,PhD,10,Government,Enterprise,USA,No,5,328616
228928,AI Engineer,18,PhD,16,Technology,Enterprise,USA,Hybrid,5,327217
182335,AI Engineer,17,PhD,18,Manufacturing,Enterprise,USA,Hybrid,5,327025
112992,AI Engineer,19,PhD,17,Manufacturing,Enterprise,USA,No,0,325052
50683,AI Engineer,20,PhD,4,Telecom,Enterprise,USA,Yes,4,324583
5971,AI Engineer,19,PhD,16,Consulting,Enterprise,USA,Yes,1,324505
241267,AI Engineer,18,PhD,15,Telecom,Enterprise,USA,No,4,323985
236878,AI Engineer,18,PhD,16,Telecom,Enterprise,USA,No,5,323423
73065,AI Engineer,17,PhD,16,Retail,Enterprise,USA,Yes,3,321127

In [37]:
df.nsmallest(10, 'salary')

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
198794,Data Analyst,0,High School,2,Retail,Startup,India,No,0,31867
183293,Data Analyst,0,High School,8,Retail,Startup,India,No,1,37213
21911,Data Analyst,2,High School,4,Healthcare,Startup,India,Hybrid,4,38779
151669,Data Analyst,0,High School,2,Consulting,Startup,India,Yes,2,39141
88603,Business Analyst,3,High School,5,Finance,Small,India,Hybrid,3,39285
207492,Data Analyst,1,High School,4,Healthcare,Small,India,Hybrid,1,39656
42849,Business Analyst,2,High School,6,Technology,Medium,India,No,1,41108
225961,Data Analyst,2,High School,1,Government,Startup,India,Yes,1,41193
28405,Data Analyst,1,Bachelor,9,Consulting,Startup,India,No,1,41276
453,Data Analyst,6,High School,1,Healthcare,Small,India,Hybrid,1,41404

In [38]:
df['salary'].max()

333046

In [39]:
df['salary'].min()

31867

In [40]:
df['salary'].mean()

np.float64(145718.080524)